# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "img/github-metrics.svg"
          
          # Options
          user: kirillzhosul
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Samara
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base_hireable: yes
          base_indepth: yes
          plugin_base_indepth: yes
          repositories_affiliations: organization_member
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "img/github-metrics-achievements.svg"
          
          # Options
          user: kirillzhosul
          template: classic
          base: ""
          config_timezone: Europe/Samara
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
